# 動作確認用ビルドの検証
name: Preview Build Verification
description: Validation before preview build

inputs:
  maven-password: # Mavenのパスワード(今のところ未使用)
    description: Maven Password
    required: false

runs:
  using: composite
  steps:
    - name: Version Verification # バージョン検証
      shell: bash
      run: |
        BRANCH="${{ github.ref_name }}"
        DEFAULT_BRANCH=`git remote show origin | grep 'HEAD branch' | awk '{print $NF}'`
        ALL_TAG=`git tag`
        LATEST_TAG=`git describe --tags --abbrev=0`
        
        chmod +x ${{ github.action_path }}/scripts/version_verification.main.kts
        ${{ github.action_path }}/scripts/version_verification.main.kts "$BRANCH" "$DEFAULT_BRANCH" "$ALL_TAG" "$LATEST_TAG"