#!/usr/bin/env kotlin

# テスト用アクション
name: Test Action
description: The Test Action

runs:
  using: composite
  steps:
    - name: Test
      shell: bash
      run: |
        echo "ｳｧｧ!!ｵﾚﾓｲｯﾁｬｳｩｩｩ!!!ｳｳｳｳｳｳｳｳｳｩｩｩｩｩｩｩｩｳｳｳｳｳｳｳｳ!ｲｨｨｲｨｨｨｲｲｲｨｲｲｲｲ"
        
        chmod +x ${{ github.action_path }}/../../../ikisugi-test.main.kts
        ${{ github.action_path }}/../../../ikisugi-test.main.kts
        
        tree ${{ github.action_path }}/../../../