on:
  workflow_call:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          pwd
          ls
      - name: ST2
        uses: TeamFelnull/actions-reusable-workflows/.github/actions/setup@master