on:
  workflow_call:
    inputs:
      before_build_tasks: #ビルド前に実行するgradleコマンド(データジェネレータの実行などに利用)
        required: false
        type: string
      build_tasks: #ビルドする際に実行するgradleコマンド
        required: true
        type: string
    secrets:
      curseforge_token: #CurseForgeのトークン
        required: false
      modrinth_token: #Modrinthのトークン
        required: false
      maven_password: #Mavenのパスワード
        required: false
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: TeamFelnull/actions-reusable-workflows/.github/actions/mcmod-setup@master

      - name: Verification
        uses: TeamFelnull/actions-reusable-workflows/.github/actions/mcmod-release-verification@master
        with:
          curseforge-token: ${{ secrets.curseforge_token }}
          modrinth-token: ${{ secrets.modrinth_token }}
          maven-password: ${{ secrets.maven_password }}

      - name: Generate Changelog
        shell: bash
        run: |
          ./gradlew patchChangelog
          ./gradlew getChangelog --console=plain -q --no-header --no-summary --no-links > LATEST_CHANGELOG.md
          
          CHANGELOG_NUM=`grep -n "^###" LATEST_CHANGELOG.md | sed -e 's/:.*//g' | head -n 1`
          if [ -n "$CHANGELOG_NUM" ]; then
            tail -n +$CHANGELOG_NUM LATEST_CHANGELOG.md > LATEST_CHANGELOG_TMP.md
            mv LATEST_CHANGELOG_TMP.md LATEST_CHANGELOG.md
          fi
          
          echo "---ChangeLog---"
          cat LATEST_CHANGELOG.md
          echo "---------------"

      - name: Build And Release
        shell: bash
        run: |
          if [ -d ./fabric ] && [ -d ./forge ]; then
          mkdir -p /home/runner/.gradle/caches/fabric-loom/assets
          fi
          
          if [ -n "${{ inputs.before_build_tasks }}" ]; then
          ./gradlew ${{ inputs.before_build_tasks }} --stacktrace --no-daemon
          fi
          
          ./gradlew ${{ inputs.build_tasks }} --stacktrace --no-daemon
        env:
          curesforgeapikey: ${{ secrets.curseforge_token }}
          modrinthapikey: ${{ secrets.modrinth_token }}
          mavenpassword: ${{ secrets.maven_password }}

      - name: Collect Releases
        shell: bash
        run: |
          mkdir release
          cd release
          
          if [ -d ../fabric/build/libs ] && [ -d ../forge/build/libs ]; then
          echo "Cloth platform..."
          cp -r ../fabric/build/libs/. ./
          cp -r ../forge/build/libs/. ./
          else
          echo "Single platform..."
          cp -r ../build/libs/. ./
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: releases
          path: release/*

      - name: GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          body_path: LATEST_CHANGELOG.md
          files: release/*