on:
  workflow_call:
    inputs:
      update_forge_version_check: #Forgeのバージョン確認用Jsonを更新するかどうか
        required: false
        type: boolean
        default: true
defaults:
  run:
    shell: bash

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: TeamFelnull/actions-reusable-workflows/.github/actions/mcmod-setup@master

      - name: Update Changelog and Version Check
        uses: TeamFelnull/actions-reusable-workflows/.github/actions/mcmod-update-changelog-versioncheck@master
        with:
          update_forge_version_check: ${{ fromJson(github.event.inputs.update_forge_version_check )}}