#動作確認用ビルドを行う
# 手動(workflow_dispatch)で実行することを前提で作成しています
name: Preview Build

on:
  workflow_call:
    inputs:
      before_build_tasks: #ビルド前に実行するgradleコマンド(データジェネレータの実行などに利用)
        required: false
        type: string
      build_tasks: #ビルドする際に実行するgradleコマンド
        required: true
        type: string
    secrets:
      maven_password: #Mavenのパスワード
        required: false
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout #チェックアウト
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup #セットアップ
        uses: TeamFelnull/actions-reusable-workflows/.github/actions/mcmod-setup@master

#      - name: Verification #検証
#        uses: TeamFelnull/actions-reusable-workflows/.github/actions/mcmod-release-verification@master
#        with:
#          curseforge-token: ${{ secrets.curseforge_token }}
#          modrinth-token: ${{ secrets.modrinth_token }}
#          maven-password: ${{ secrets.maven_password }}

      - name: Build And Release #ビルド
        shell: bash
        run: |
          if [ -d ./fabric ] && [ -d ./forge ]; then
          mkdir -p /home/runner/.gradle/caches/fabric-loom/assets
          fi
          
          if [ -n "${{ inputs.before_build_tasks }}" ]; then
          ./gradlew ${{ inputs.before_build_tasks }} --stacktrace --no-daemon
          fi
          
          ./gradlew ${{ inputs.build_tasks }} --stacktrace --no-daemon
        env:
          mavenpassword: ${{ secrets.maven_password }}

      - name: Collect Releases #リリースするファイルを収集
        shell: bash
        run: |
          mkdir release
          cd release
          
          if [ -d ../fabric/build/libs ] && [ -d ../forge/build/libs ]; then
          echo "Cloth platform..."
          cp -r ../fabric/build/libs/. ./
          cp -r ../forge/build/libs/. ./
          else
          echo "Single platform..."
          cp -r ../build/libs/. ./
          fi

      - name: Generate Hash #リリースするファイルのハッシュファイルを生成
        uses: TeamFelnull/actions-reusable-workflows/.github/actions/hashing-directory@master
        with:
          directory_path: "${{ github.workspace }}/release"

      - name: Upload Artifact #アーティファクトをアップロード
        uses: actions/upload-artifact@v3
        with:
          name: releases
          path: release/*